# Generated by Django 4.0.6 on 2022-10-12 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetails', '0003_alter_department_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='schoolDetails.school'),
        ),
    ]
