# Generated by Django 4.0.6 on 2022-10-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolDetails', '0005_alter_unitdetails_registration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetails',
            name='registration_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=255, null=True),
        ),
    ]
