# Generated by Django 4.0.6 on 2022-10-14 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_lecturer_staff_id_alter_student_reg_no'),
        ('schoolDetails', '0010_alter_unitdetails_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitdetails',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='account.student'),
        ),
    ]
