# Generated by Django 4.0.6 on 2022-10-15 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_lecturer_staff_id_alter_student_reg_no'),
        ('schoolDetails', '0015_alter_studenthostel_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthostel',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Complete'), ('F', 'Failed')], default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='studenthostel',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='account.student'),
        ),
    ]
